package de.oth.blocklib.textures;

import java.nio.ByteBuffer;

/**
 * Hold all values for a texture
 * @see ModelTexture
 */
public class Texture {
	
	int TextureID;
	int width;
	int height;
	ByteBuffer buf;

	/**
	 * All values of the texture as one object.
	 * @param textureID id generated by opengl
	 * @param width width of the texture
	 * @param height height of the texture
	 * @param buf buffer with the texture.
	 */
	public Texture(int textureID, int width, int height, ByteBuffer buf) {
		super();
		TextureID = textureID;
		this.width = width;
		this.height = height;
		this.buf = buf;
	}

	/**
	 * Get the id of the texture, generated by opengl.
	 * @return id of the texture.
	 */
	public int getTextureID() {
		return TextureID;
	}

}
